"""Rebuild data/products.js (what the pages load) from data/products.json (the editable catalogue).

Edit products in data/products.json, then run:  python tools/build-products-js.py
Only fields the site displays are written, and empty fields are omitted to keep the file small.
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC, OUT = os.path.join(ROOT, 'data', 'products.json'), os.path.join(ROOT, 'data', 'products.js')
# Internal migration fields (review, descTruncated, descSource, sourceStock, sourceImage, sourceUrl) stay in products.json only.
KEYS = ['id', 'partNumber', 'sap', 'category', 'name_en', 'name_ar', 'desc_en', 'desc_ar', 'image', 'condition']
HEAD = ('/* Velmach Aerospace catalogue data, generated from data/products.json by tools/build-products-js.py. Do not edit by hand:\n'
        '   edit data/products.json and rebuild. Holds only the fields the site displays; empty fields are omitted.\n'
        '   Fields: id (URL slug, see js/routes.js), partNumber, sap, category, name_en/name_ar, desc_en/desc_ar,\n'
        '   image (assets/products/...), condition. */\n')

products = json.load(open(SRC, encoding='utf-8'))
ids = [p['id'] for p in products]
dupes = {i for i in ids if ids.count(i) > 1} if len(set(ids)) != len(ids) else set()
if dupes: raise SystemExit('Duplicate product ids: ' + ', '.join(sorted(dupes)))
for p in products:
    if not p.get('id') or not p.get('partNumber') or not p.get('category'):
        raise SystemExit('Every product needs id, partNumber and category: ' + json.dumps(p, ensure_ascii=False)[:200])
lines = [json.dumps({k: p[k] for k in KEYS if p.get(k) not in (None, '')}, ensure_ascii=False, separators=(',', ':')) for p in products]
open(OUT, 'w', encoding='utf-8').write(HEAD + 'window.VM_PRODUCTS = [\n' + ',\n'.join(lines) + '\n];\n')
print(f'{len(products)} products -> data/products.js ({os.path.getsize(OUT) // 1024} KB)')

# one sitemap entry per product page, same URL style as sitemap.xml (TODO: replace domain there and here)
from urllib.parse import quote
from xml.sax.saxutils import escape
SITE = 'https://www.velmachaerospace.com/product.html?p='
def url(p):
    u = SITE + quote(p['id'])
    return (f'  <url><loc>{escape(u)}</loc><xhtml:link rel="alternate" hreflang="en" href="{escape(u + "&lang=en")}"/>'
            f'<xhtml:link rel="alternate" hreflang="ar" href="{escape(u + "&lang=ar")}"/></url>')
open(os.path.join(ROOT, 'sitemap-products.xml'), 'w', encoding='utf-8').write(
    '<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by tools/build-products-js.py. TODO: replace domain -->\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
    + '\n'.join(url(p) for p in products) + '\n</urlset>\n')
print(f'{len(products)} product URLs -> sitemap-products.xml')
